import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <GoogleOAuthProvider clientId="759324330580-t9vol25lj0q6r5vavff2o9vksisesof6.apps.googleusercontent.com">
      <html lang="en">
        <head>
          <title>picker</title>
          <meta name="description" content={"picker"} />
        </head>
        <body className={inter.className}>
          <div>{children}</div>
          <Toaster />
        </body>
      </html>
    </GoogleOAuthProvider>
  );
};

export default RootLayout;
