export const categories: string[] = [
  "Newspaper",
  "Books",
  "Plastic",
  "Cardboard",
  "Iron",
  "Steel",
  "Copper",
  "Aluminium",
  "Brass",
  "Metal Appliances Light (DVD/CD/VCR/BluRay Player/Clothes Press/Set Top Box/Iron Cooler/Iron Exhaust Fan/Microwave/Geyser with Steel Tank/Chimney)",
  "Metal Appliances Heavy (Motor/Stabiliser/Ceiling Fan/Inverter/UPS)",
  "Plastic Appliances (Plastic cooler, Vaccum Cleaner, Mixer, Induction Cooktop, Plastic Exhaust Fan, Router/Modem)",
  "Printer/scanner/fax machine/LCD TV/LED TV",
  "Battery (Used with Inverters)",
  "Window or Split AC (1Ton)",
  "Window or Split AC (1.5 Ton)",
  "Window or Split AC (2 Ton)",
  "Single Door Fridge",
  "Double Door Fridge",
  "Semi Automatic Washing Machine (Double Drum)",
  "Fully Automatic Washing Machine(Top Load)",
  "Fully Automatic Washing Machine(Front Load)",
  "Feature Phone",
  "Tablet",
  "Laptop",
  "Computer CPU",
  "Monitor/CRT TV",
  "Miscellaneous",
  "Glass",
];

export const subCategories: string[] = [
  "Newspaper",
  "Books",
  "Plastic",
  "Cardboard",
  "Iron",
  "Steel",
  "Copper",
  "Aluminium (Normal)",
  "Aluminium (Mixed)",
  "Brass",
  "Plastic Appliances Light",
  "Plastic Appliances Heavy",
  "Metal Appliances Light",
  "Metal Appliances Medium",
  "Metal Appliances Heavy",
  "Printer/scanner/fax machine/LCD TV/LED TV",
  "Wire Scrap (Mixed)",
  "Wire Scrap (Fitting)",
  "Battery (Used with Inverters)",
  "Battery Dry",
  "Window or Split AC (1Ton)",
  "Window or Split AC (1.5 Ton)",
  "Window or Split AC (2 Ton)",
  "Single Door Fridge",
  "Double Door Fridge",
  "Semi Automatic Washing Machine (Double Drum)",
  "Fully Automatic Washing Machine (Top Load)",
  "Fully Automatic Washing Machine (Front Load)",
  "Bike",
  "Scooty",
  "Scooter",
  "Laptop",
  "Computer CPU",
  "Monitor/CRT TV",
  "Glass",
  "Tod Fod (Plastic)",
  "Tod Fod (<50)",
  "Tod Fod (50-150)",
  "Tod Fod (150-300)",
  "Tod Fod (>300)",
];
